---

- name: disable default audio driver
  lineinfile:
    path: /boot/config.txt
    regexp: '^#?dtparam=audio=on'
    line: '#dtparam=audio=on'
  notify:
    - reboot host

- name: enable gidiberry audio driver
  lineinfile:
    path: /boot/config.txt
    insertafter: '^#?dtparam=audio=on'
    line: 'dtoverlay=hifiberry-dacplus'
  notify:
    - reboot host

- name: enable alsa
  copy:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items:
    - { src: "hifiberry/asound.conf",
        dest: "/etc/asound.conf",
        owner: "root",
        group: "root",
        mode: "0600"}
  notify:
    - reboot host

- name: configure Master Volume to 100%
  command: amixer cset numid=1 100%
